name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: checkboxes
    id: existing
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched the existing issues and this bug has not been reported
          required: true
        - label: I am using the latest version of LabelLoad
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I try to... the application...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Open the application
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Application Version
      description: LabelLoad version number
      placeholder: "1.0.4"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Debian 12
        - Linux Mint
        - Other Linux Distribution
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Installation Type
      options:
        - CPU Package (.deb)
        - GPU Package (.deb)
        - Built from source
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error logs or terminal output
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
